spring:
  profiles:
    active: dev


#logging:
#  level:
#    com:
#      MAQ:
#        JournalApp: INFO


          #all the logs having severity greater than debug will also be printed along with debug .
                                  #Severity level:- error > warn > info > debug > trace
