spring:
  application:
    name: JournalApp
  data:
    mongodb:
      uri: mongodb+srv://singhpiyush8128:nGgyaIu8i0Av6nE0@cluster0.v8r5x.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      #uri: mongodb+srv://singhpiyush8128:trkpAmGE0jFavn9L@cluster01.ol38q.mongodb.net/?retryWrites=true&w=majority&appName=Cluster01
      #uri: mongodb+srv://singhpiyush8128:piyush41@cluster41.zxvse.mongodb.net/?retryWrites=true&w=majority&appName=Cluster41
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: singhpiyush8128@gmail.com
    password: xmxt kgtl fmrm swcj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /journal


weather:
  api:
    key: 85eda8f5a9484a33a3c103747252002



